FROM python:3.9-slim
WORKDIR /app
COPY . .
CMD ["python3", "app.py"]





















Create folder: maven_project
Open Command Prompt

mvn --version
mvn archetype:generate
<Enter>

groupId    : com.bnmit
artifactId : sample-app
package    : com.bnmit
Y <Enter>

cd sample-app
mvn clean
mvn package

cd target
dir

java -cp sample-app-1.0-SNAPSHOT.jar com.bnmit.App
